from __future__ import annotations


MQTT_MEASUREMENTS_TOPIC_BASE = "comp5339/task123/measurements"
MQTT_PUBLISH_TOPIC_TEMPLATE = f"{MQTT_MEASUREMENTS_TOPIC_BASE}/{{facility_code}}"
MQTT_SUBSCRIBE_TOPIC_FILTER = f"{MQTT_MEASUREMENTS_TOPIC_BASE}/#"


__all__ = [
    "MQTT_MEASUREMENTS_TOPIC_BASE",
    "MQTT_PUBLISH_TOPIC_TEMPLATE",
    "MQTT_SUBSCRIBE_TOPIC_FILTER",
]
